name: Language Badge Request
description: Submit your repo for language badge generation
title: Language badge request
labels:
  - badge-request
body:
  - type: input
    id: repo
    attributes:
      label: Create a language badge
      description: Enter the GitHub repository name in format "user/repo"
      placeholder: tbwcjw/languages-badge
    validations:
      required: true